version: "3.9"
services:
  natty_sh:
    build:
      context: ./nginx-docker
      dockerfile: Dockerfile
    networks:
      - natty-php-network
    volumes:
      - ./natty-web:/www/natty.sh/
    ports:
      - "8081:80"
    depends_on:
      - natty_sh_php
  natty_sh_php:
    image: php:fpm-alpine
    networks:
      - natty-php-network
    volumes:
      - ./natty-web:/www/natty.sh/
networks:
  natty-php-network:
    driver: bridge
